export const apis: API[] = [
    {
        id: "openai",
        name: "OpenAI API",
        description: "Access powerful language models like GPT-3 and GPT-4",
        category: "Machine Learning",
        apiLink: "https://api.openai.com/v1",
        documentation: "https://platform.openai.com/docs/api-reference",
    },
    {
        id: "stripe",
        name: "Stripe API",
        description: "Process payments and manage financial transactions",
        category: "Finance",
        apiLink: "https://api.stripe.com/v1",
        documentation: "https://stripe.com/docs/api",
    },
    {
        id: "twilio",
        name: "Twilio API",
        description: "Add messaging, voice, and video capabilities to applications",
        category: "Communication",
        apiLink: "https://api.twilio.com/2010-04-01",
        documentation: "https://www.twilio.com/docs/api",
    },
    {
        id: "googlemaps",
        name: "Google Maps API",
        description: "Integrate maps and location services into your projects",
        category: "Geolocation",
        apiLink: "https://maps.googleapis.com/maps/api",
        documentation: "https://developers.google.com/maps/documentation",
    },
    {
        id: "spotify",
        name: "Spotify API",
        description: "Access music metadata and control playback",
        category: "Entertainment",
        apiLink: "https://api.spotify.com/v1",
        documentation: "https://developer.spotify.com/documentation/web-api",
    },
    {
        id: "github",
        name: "GitHub API",
        description: "Interact with repositories, issues, and pull requests",
        category: "Development",
        apiLink: "https://api.github.com",
        documentation: "https://docs.github.com/en/rest",
    },
    {
        id: "sendgrid",
        name: "SendGrid API",
        description: "Send transactional and marketing emails",
        category: "Communication",
        apiLink: "https://api.sendgrid.com/v3",
        documentation: "https://docs.sendgrid.com/api-reference",
    },
    {
        id: "slack",
        name: "Slack API",
        description: "Build integrations for Slack workspaces",
        category: "Communication",
        apiLink: "https://slack.com/api",
        documentation: "https://api.slack.com/",
    },
    {
        id: "shopify",
        name: "Shopify API",
        description: "Create and manage e-commerce stores and products",
        category: "E-commerce",
        apiLink: "https://shopify.dev/docs/api/admin-rest",
        documentation: "https://shopify.dev/docs/api/admin-rest",
    },
    {
        id: "linkedin",
        name: "LinkedIn API",
        description: "Access professional network data and share content",
        category: "Social Media",
        apiLink: "https://api.linkedin.com/v2",
        documentation: "https://docs.microsoft.com/en-us/linkedin/",
    },
    {
        id: "dropbox",
        name: "Dropbox API",
        description: "Integrate cloud storage and file sharing capabilities",
        category: "Cloud Storage",
        apiLink: "https://api.dropboxapi.com/2",
        documentation: "https://www.dropbox.com/developers/documentation",
    },
    {
        id: "twitter",
        name: "Twitter API",
        description: "Access and interact with Twitter data",
        category: "Social Media",
        apiLink: "https://api.twitter.com/2",
        documentation: "https://developer.twitter.com/en/docs/twitter-api",
    },
    {
        id: "aws",
        name: "Amazon Web Services (AWS) API",
        description: "Access various cloud computing services",
        category: "Cloud Computing",
        apiLink: "https://docs.aws.amazon.com/general/latest/gr/aws-apis.html",
        documentation: "https://docs.aws.amazon.com/",
    },
    {
        id: "azure",
        name: "Microsoft Azure API",
        description: "Integrate cloud services and manage Azure resources",
        category: "Cloud Computing",
        apiLink: "https://management.azure.com",
        documentation: "https://docs.microsoft.com/en-us/rest/api/azure/",
    },
    {
        id: "googlecloud",
        name: "Google Cloud API",
        description: "Access Google Cloud services and resources",
        category: "Cloud Computing",
        apiLink: "https://cloud.google.com/apis",
        documentation: "https://cloud.google.com/apis/docs/overview",
    },
    {
        id: "hubspot",
        name: "HubSpot API",
        description: "Manage customer relationships and marketing automation",
        category: "CRM",
        apiLink: "https://api.hubapi.com/",
        documentation: "https://developers.hubspot.com/docs/api/overview",
    },
    {
        id: "salesforce",
        name: "Salesforce API",
        description: "Access and manage customer data in Salesforce",
        category: "CRM",
        apiLink: "https://login.salesforce.com/services/oauth2/token",
        documentation: "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_what_is_rest_api.htm",
    },
    {
        id: "jira",
        name: "Jira API",
        description: "Manage projects, issues, and workflows in Jira",
        category: "Project Management",
        apiLink: "https://your-domain.atlassian.net/rest/api/3",
        documentation: "https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/",
    },
    {
        id: "trello",
        name: "Trello API",
        description: "Interact with boards, lists, and cards in Trello",
        category: "Project Management",
        apiLink: "https://api.trello.com/1",
        documentation: "https://developer.atlassian.com/cloud/trello/rest/api-group-actions/",
    },
    {
        id: "instagram",
        name: "Instagram Graph API",
        description: "Access Instagram features and user data",
        category: "Social Media",
        apiLink: "https://graph.instagram.com",
        documentation: "https://developers.facebook.com/docs/instagram-api/",
    },
    {
        id: "youtube",
        name: "YouTube Data API",
        description: "Integrate YouTube functionalities into your application",
        category: "Entertainment",
        apiLink: "https://www.googleapis.com/youtube/v3",
        documentation: "https://developers.google.com/youtube/v3",
    },
    {
        id: "paypal",
        name: "PayPal API",
        description: "Integrate PayPal payments into your application",
        category: "Finance",
        apiLink: "https://api.paypal.com",
        documentation: "https://developer.paypal.com/api/rest/",
    },
    {
        id: "digitalocean",
        name: "DigitalOcean API",
        description: "Manage cloud infrastructure and services",
        category: "Cloud Computing",
        apiLink: "https://api.digitalocean.com/v2",
        documentation: "https://developers.digitalocean.com/documentation/v2/",
    },
    {
        id: "cloudflare",
        name: "Cloudflare API",
        description: "Manage Cloudflare services and configurations",
        category: "Web Infrastructure",
        apiLink: "https://api.cloudflare.com/client/v4",
        documentation: "https://developers.cloudflare.com/api/",
    },
    {
        id: "zoom",
        name: "Zoom API",
        description: "Integrate video conferencing and messaging features",
        category: "Communication",
        apiLink: "https://api.zoom.us/v2",
        documentation: "https://marketplace.zoom.us/docs/guides",
    },
    {
        id: "notion",
        name: "Notion API",
        description: "Access and manage Notion workspace data",
        category: "Productivity",
        apiLink: "https://api.notion.com/v1",
        documentation: "https://developers.notion.com/docs",
    },
    {
        id: "figma",
        name: "Figma API",
        description: "Automate design workflows and access Figma files",
        category: "Design",
        apiLink: "https://api.figma.com/v1",
        documentation: "https://www.figma.com/developers/api",
    },
    {
        id: "wikipedia",
        name: "Wikipedia API",
        description: "Access and query Wikipedia content",
        category: "Knowledge",
        apiLink: "https://en.wikipedia.org/w/api.php",
        documentation: "https://www.mediawiki.org/wiki/API:Main_page",
    },
    {
        id: "discord",
        name: "Discord API",
        description: "Build bots and integrate with Discord servers",
        category: "Communication",
        apiLink: "https://discord.com/api/v10",
        documentation: "https://discord.com/developers/docs/intro",
    },
    {
        id: "weather",
        name: "Weather API",
        description: "Get weather data and forecasts",
        category: "Weather",
        apiLink: "https://api.openweathermap.org/data/2.5",
        documentation: "https://openweathermap.org/api",
    },
    {
        id: "newsapi",
        name: "News API",
        description: "Access news articles from various sources",
        category: "News",
        apiLink: "https://newsapi.org/v2",
        documentation: "https://newsapi.org/docs/endpoints",
    },
    {
        id: "firebase",
        name: "Firebase API",
        description: "Build real-time applications with Firebase services",
        category: "Backend",
        apiLink: "https://firebase.google.com/docs/reference/rest",
        documentation: "https://firebase.google.com/docs",
    },
    {
        id: "pinterest",
        name: "Pinterest API",
        description: "Access Pinterest pins, boards, and user data",
        category: "Social Media",
        apiLink: "https://api.pinterest.com/v1",
        documentation: "https://developers.pinterest.com/docs/getting-started/",
    },
    {
        id: "mailgun",
        name: "Mailgun API",
        description: "Send, receive, and track emails",
        category: "Communication",
        apiLink: "https://api.mailgun.net/v3",
        documentation: "https://documentation.mailgun.com/en/latest/api_reference.html",
    },
    {
        id: "algebrapi",
        name: "AlgebrAPI",
        description: "Solve algebraic equations and math problems",
        category: "Mathematics",
        apiLink: "https://api.algebrapi.com/v1",
        documentation: "https://www.algebrapi.com/docs/",
    },
    {
        id: "coinbase",
        name: "Coinbase API",
        description: "Access cryptocurrency exchange services, retrieve market data, manage wallets, and execute trades",
        category: "Cryptocurrency",
        apiLink: "https://api.coinbase.com/v2",
        documentation: "https://developers.coinbase.com/docs/wallet/",
    },
    {
        id: "rapidapi",
        name: "RapidAPI",
        description: "Access thousands of APIs for various services",
        category: "API Marketplace",
        apiLink: "https://rapidapi.com/",
        documentation: "https://rapidapi.com/docs",
    },
]
